version: '3'

services:
  nginx-puma:
    container_name: xwiki-nginx
    image: juanico/nginx-puma:xwiki
    restart: unless-stopped
    volumes:
      - './xwiki-data:/var/www/html'
    depends_on:
      - backend
    ports:
        - '80:80'

  backend:
    image: "xwiki:stable-postgres-tomcat"
    container_name: xwiki
    depends_on:
      - db
      - backend-cache
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_DATABASE=xwiki
      - DB_HOST=xwiki-postgres-db
	  - TZ=Europe/Madrid
    volumes:
      - ./xwiki-data:/usr/local/xwiki

  db:
    image: "postgres:alpine"
    container_name: xwiki-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_ROOT_PASSWORD=xwiki
      - POSTGRES_PASSWORD=xwiki
      - POSTGRES_USER=xwiki
      - POSTGRES_DB=xwiki
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"

  backend-cache:
    image: redis:alpine
    container_name: xwiki-redis
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped