--- 
version: "3.3" 
  
volumes: 
  duplicati: 
    driver: local 
  
services: 
  duplicati: 
    image: lscr.io/linuxserver/duplicati 
    container_name: duplicati 
    restart: always 
    networks: 
      - red 
    environment: 
      - PUID=0
      - PGID=0
      - TZ=Europe/Madrid 
    labels:
      - traefik.enable=true
      - traefik.http.services.codimd.loadbalancer.server.port=8200
      - traefik.http.routers.codimd.entrypoints=web
      - traefik.http.routers.codimd.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.codimd-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.codimd.middlewares=codimd-https-redirect
      - traefik.http.routers.codimd-secure.entrypoints=websecure
      - traefik.http.routers.codimd-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.codimd-secure.tls=true
      - traefik.http.routers.codimd-secure.tls.certresolver=letsencrypt
    volumes: 
      - /patch/to/data/duplicati/config:/config 
      - /home/${USER}:/home
      - /mnt/hdd:/hdd
  
networks: 
  red: 
    external: true