---
version: "3"

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    environment:
      - APP_URL=${URL}
      - DB_HOST=bookstack-db:3306
      - DB_USER=${USER}
      - DB_PASS=${PASS}
      - DB_DATABASE=${DATABASE}
    volumes:
      - ./bookstack:/config
    restart: always
    depends_on:
      - bookstack-db
    labels:
      - traefik.enable=true
      - traefik.http.services.codimd.loadbalancer.server.port=3000
      - traefik.http.routers.codimd.entrypoints=web
      - traefik.http.routers.codimd.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.codimd-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.codimd.middlewares=codimd-https-redirect
      - traefik.http.routers.codimd-secure.entrypoints=websecure
      - traefik.http.routers.codimd-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.codimd-secure.tls=true
      - traefik.http.routers.codimd-secure.tls.certresolver=letsencrypt
    networks:
      - proxy
      - internal

  bookstack-db:
    restart: always
    image: mariadb:focal
    container_name: bookstack-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    networks:
      - internal
    environment:
      - TZ=Europe/Madrid
      - MYSQL_ROOT_PASSWORD=${PASS}
      - MYSQL_PASSWORD=${PASS}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER}
    volumes:
      - ./bookstack_db:/var/lib/mysql
    labels:
      - traefik.enable=false


networks:
  proxy:
    external: true
  internal:
    external: false
