version: '3.7' 
  
  
services: 
  influxdb: 
    image: influxdb 
    container_name: influxdb 
    volumes: 
      - /patch/to/data/influxdb/data:/var/lib/influxdb
      - /patch/to/data/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf 
    networks: 
      - red 
      - internal 
    labels:
      - traefik.enable=true
      - traefik.http.services.influxdb.loadbalancer.server.port=3000
      - traefik.http.routers.influxdb.entrypoints=web
      - traefik.http.routers.influxdb.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.influxdb-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.influxdb.middlewares=influxdb-https-redirect
      - traefik.http.routers.influxdb-secure.entrypoints=websecure
      - traefik.http.routers.influxdb-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.influxdb-secure.tls=true
      - traefik.http.routers.influxdb-secure.tls.certresolver=letsencrypt
  
  grafana: 
    image: grafana/grafana 
    container_name: grafana 
    environment: 
      - GF_SERVER_ROOT_URL=https://grafana.example.com 
      - GF_EXTERNAL_IMAGE_STORAGE=local 
      - GF_INSTALL_PLUGINS=grafana-piechart-panel 
    networks: 
      - red 
      - internal 
    volumes: 
      - /patch/to/data/grafana/data:/var/lib/grafana 
    labels: 
      - "traefik.backend=grafana" 
      - "traefik.enable=true" 
      - "traefik.frontend.rule=Host:grafana.example.com" 
      - "traefik.port=3000" 
      - "traefik.docker.network=red" 
  
  telegraf: 
    image: telegraf:latest 
    container_name: telegraf 
    volumes: 
      - /patch/to/data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  prometheus: 
    image: prom/prometheus:latest 
    container_name: prometheus 
    volumes: 
      - /patch/to/data/prometheus/data:/prometheus 
      - /patch/to/data/prometheus/etc:/etc/prometheus 
    networks: 
      - internal 