version: '3'
services:
   webdav:
    image: juanico/webdav:latest
    container_name: webdav
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      # montar carpeta compartida
      - /patch/to/data/srv:/share
      # montar nombre de usuario y contraseña
      - /patch/to/data/htpasswd:/opt/nginx/conf/.htpasswd
    ports:
        - '8080:8080'
